### ISSUE TITLE
GPU 

### ISSUE THREAD

**Issue by m1996** [Vanint/TADE-AgnosticLT#1]
hello.
very sorry for commenting here, my question is from ppn portfolio which its issues is closed and I had no other way to ask from you.
i tried to run that project on google colab but it took so much time which colab doesn't accept. i figured out that tensorflow 1.4.0 doesn't use gpu. is there any solution for that? i tried so much but i got no answer. please help me.
and if there is anything that i should consider while using colab for that project, please remind me.

regards

**Comment by YifanZhang07** [comment]
Hi, I have not used google colab so I am not familiar with it. Which part is time-consuming? Data processing or optimization?

**Comment by m1996** [comment]
Thank you so much for your reply, All of that is time consuming. I changed
the code to print the number of each step and it took more than 4 hours for
137 steps in training (and the 'steps' in config is 10000!). And I saw that
the tf.device_name() shows nothing which means it doesn't use the gpu.
Should I install sth special for that? I install all the requirements as
you said in the readme file(for example you said tensorflow>=1.4.0 and I
install tensorflow=1.4.0).
Would you please tell me a good config to train faster? Or give me a brief
explanation for each config parameters so I change them properly.

Regards

**Comment by YifanZhang07** [comment]
In fact, I did not encounter this problem, where I conduct experiments on the sever with four Titan X GPUs. I think the reasons may lie on the gpu platform or python packages. Can you find any private server to verify the first factor? Moreover, have you tried to install tensorflow-gpu?

**Comment by m1996** [comment]
I installed tensorflow-gpu=1.4
And cuda 8 and cudnn 6
But still doesn't work:(
Did I install right versions?

**Comment by YifanZhang07** [comment]
I guess so. Since I have left the previous school, the server I used has been modified, so I cannot access it to confirm the details. In addition to finding a private server, one more suggestion is that you can first try the code in EIIE (https://github.com/ZhengyaoJiang/PGPortfolio), since our method is developed based on this repository. If it works, then you can change the method part to our method.

**Comment by m1996** [comment]
Aha, thanks a lot.
Can I use other versions of tensorflow?Should tensorflow-gpu version be 1.4?

**Comment by YifanZhang07** [comment]
Sure, if it works.

**Comment by m1996** [comment]
Thanks a lot for your guides.
Wish you always be happy and healthy :)

**Comment by m1996** [comment]
hello.
again very sorry for commenting here, my question is from ppn portfolio which its issues is closed and I had no other way to ask from you.
I fixed the gpu problem, and trained the agent but 1000 step by 1000 step (due to google colab limits) by using restore dir. but the results were so weird. The APV was 49000!! I figured out the omega (portfolio weights) got negative values which is not usual. do you have any idea why it happens?
I thought its because of decision making module(as you commented: three strategies to make decision, where the leverage operation is beyond the version of the paper.) which uses 2-head leverage operation. so I changed it to fully connected layer. and after 5000 steps, the result has no change with a very small value. can you help me? where have I gone wrong?

regards

**Comment by YifanZhang07** [comment]
Hi, the performance depends on many reasons, like data split (sometimes network may learn shortcut, which is hard to explain in Deep RL), training scheme, and so on.  Therefore, I have no idea about the real reason, since it, at least, does not collapse. How about downloading another piece of data for finding a more reasonable benchmark (i.e., modifying operations can lead to more significant change), which may be a solution if you cannot handle it in the end.

Yes, the negative portfolio weight is due to the leverage operation; removing it leads to all positive values.

**Comment by m1996** [comment]
thank you so much
actually that the results were sooo different from what reported in the paper, was strange for me.
I will check more closely again and if I run into anything, I will bother you again:)
regards

**Comment by m1996** [comment]
Hi again😅
I tried the code with another period of time of S&P500 prices, still I just
got 1.5 for portfolio value:( AND it converges so fast in about 500 steps!
Is it normal? Do you have any suggestion please?

**Comment by YifanZhang07** [comment]
I cannot remember the convergence speed exactly, since it is quite an old project.

**Comment by m1996** [comment]
Thanks, in the paper it said 100000 steps! 15 hours!
